---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carapi
  namespace: cluster-config
spec:
  targetNamespace: carapi
  releaseName: carapi
  chart:
    spec:
      chart: carapi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: carapi
        namespace: cluster-config
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: nginx
    service:
      type: ClusterIP
    replicaCount: 2