# root path
GET http://marvaks.eastus2.cloudapp.azure.com/userapi

###

# swagger page
GET http://marvaks.eastus2.cloudapp.azure.com/userapi/swagger

###

# Users
GET http://marvaks.eastus2.cloudapp.azure.com/userapi/api/users