e4kdmqtt:
  broker:
    frontend:
      replicas: 2
    backend:
      replicas: 2
      chainCount: 2
  authentication:
    credentials:
      configToml: |
        [client1]
        password = "$argon2i$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$ZZ/eAcHRleU4ChG0EJ+2Mw"

        [client1.attributes]
        floor = "floor1"
        site = "site1"

connector:
  enabled: true

e4kconnector:
  kafka:
    endpoint: eh-ec2db7b3.servicebus.windows.net:9093
    group_id_prefix: e4kconnector
    auto_commit_interval_ms: 5000
    auth:
      type: plain
      username: $ConnectionString
      password: Endpoint=sb://eh-ec2db7b3.servicebus.windows.net/;SharedAccessKeyName=send;SharedAccessKey=trfPDAaxO4cLXS7IUzocHrA/nivilsV90wGeBaOX5do=;EntityPath=e4k-ingress
  topicMap:
    configYaml:
      route:
        # A route defined to pull from mqtt topic "topic1" and push to Kafka topic "e4k-ingress" (default - partition 0 only)
        - kafka: e4k-ingress
          mqtt: topic1
          sink_to: kafka # key that dictates direction